### ISSUE TITLE
SMC - erro ao inserir status do documento do proponente

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#107]
Quando a SMC vai analisar um cadastro e escolhe os status dos documentos, ao atualizar dá erro de idPf na linha 24 do documento smc_visualiza_perfil_pf.php e não mostra mensagem de atualizado com sucesso

**Comment by grayce1220** [comment]
[erro id 107.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563801235ef3264700527c74/125516c66e82c728ace21e0d46ed86882cc28aadcfb8ef14e611b2843b492d762a10e17132d0e17fb9127a020e5e1aae10515844fcf8dd2cf4e03571884e17ff933c0120996048e6edc00db513bb29814e80b5b48e4cc6e13f26e688895d73.docx)

**Comment by grayce1220** [comment]
[erro id 107.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563801235ef3264700527c74/125516c66e82c728ace21e0d46ed86882cc28aadcfb8ef14e611b2843b492d762a10e17132d0e17fb9127a020e5e1aae10515844fcf8dd2cf4e03571884e17ff933c0120996048e6edc00db513bb29814e80b5b48e4cc8ef3c20e688895d73.docx)

**Comment by DiegoVSantos** [comment]
**O que foi Feito:** Retirado o uso da variavel $_GET['idPf']

**Comment by grayce1220** [comment]
Solucionado

**Comment by DiegoVSantos** [comment]
Teste OK!
