### ISSUE TITLE
SMC - Inscrições de pessoa física a liberar

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#108]
Não permitir aprovar ou reprovar sem colocar os status nos documentos
?perfil=smc_visualiza_perfil_pf
?perfil=smc_visualiza_perfil_pj
?perfil=smc_visualiza_incentivadores_pf
?perfil=smc_visualiza_incentivadores_pj

**Comment by DiegoVSantos** [comment]
**OK** - ?perfil=smc_visualiza_perfil_pf
**OK** - ?perfil=smc_visualiza_perfil_pj

**Comment by grayce1220** [comment]
Task cancelada a pedido da SMC.
