### ISSUE TITLE
Modal de Renúncia Fiscal

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#115]
- Erro: primeira “Aba” do modal de “Renúncia Fiscal” não volta após clicar em outra “Aba”

[BUG_ID_115_CADASTRO_DE_PROJETO_V0.9.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7efa5324364700133ca753/125516c66e82c728ace21e0d46caa1bd1caba796deb8ea7c877cd4b51a72155c1620861440b7cc029a76543e395f50a553444d04bea6d37ef5f22e7a985959ea876d0e27973c45aee98b18bf01bb748c1dd3bfbd885edcfa7f74b9dfd0126754505a9bf54f34a7934acd5bfe4fe04550a5163763ef647b.docx)

**Comment by riquetinem** [comment]
e la vamos nós

**Comment by grayce1220** [comment]
TESTE OK
