### ISSUE TITLE
Permitir exclusão de documentos que o proponente anexou no projeto (complemento, solicitação de alteração, etc)

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#121]
No módulo SMC, na aba administrativo, permitir o cancelamento dos documentos através do campo "publicado = 0", permitindo que o proponente anexe outro arquivo.
Esse tipo de cancelamento deve ter tela de confirmação avisando que a ação não pode ser desfeita e registrar numa tabela de histórico

**Comment by LoreleiGab** [comment]
O que foi feito:
Criado uma lista onde mostra todos os documentos que o usuário pode subir em relação ao projeto (idListaDocumento id's  39,40,41,42,43,44,46,47,52,53). Essa lista contém um botão de Remover que transforma o arquivo em publicado = 0, mas isso só depois que confirmado via modal.

**Comment by grayce1220** [comment]
Na SMC não exibe a listagem de "Solicitações do proponente", apenas na COMISSÃO.
O certo (confirmado com a Lore) é exibir em ambos os níveis de acesso, SEM O BOTÃO DE APAGAR.

**Comment by grayce1220** [comment]
A listagem depende de um switch case que seleciona o id do arquivo a ser listado dependendo do status do projeto. para aplicar essa alteração para a SMC, deve ser revisto o switch.

**Comment by grayce1220** [comment]
Revendo task #135

**Comment by grayce1220** [comment]
Task #135 corrigida
