### ISSUE TITLE
Na Consulta Pública, ao buscar todos os projetos aprovados, aparece uma lista de apenas 50 projetos, enquanto pelo nosso controle das publicações em Diário Oficial temos 58 projetos aprovados. Um exemplo que vi que não está aparecendo no sistema é o projeto SuperNova.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#127]

**Comment by DiegoVSantos** [comment]
Nossa base de homologação até o presente momento, foi criada dia 01/10/2018 às 11:15, onde haviam apenas 50 projetos aprovados. O projeto citado como exemplo teve seu status alterado para "Aprovado" após esta data.
