### ISSUE TITLE
Protocolos sem ter projeto enviado

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#130]
2018090600170
2018090600047
2018090600248

**Comment by LoreleiGab** [comment]
[Uploading WhatsApp Image 2018-10-03 at 12.03.09.jpeg...]
[Uploading WhatsApp Image 2018-10-03 at 12.07.46.jpeg...]
[Uploading WhatsApp Image 2018-10-03 at 12.08.15.jpeg...]

**Comment by grayce1220** [comment]
Teste ok
