### ISSUE TITLE
SMC - Aba inscrição

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#133]
Mesmo quando aprovado ou reprovado, precisa continuar carregando a lista dos documentos conforme imagem anexa

**Comment by LoreleiGab** [comment]
![Capturar2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563b68cd746ae64300e4e6d5/125516c66e82c728ace21e0d46cb958a379791a89dbbfd0fe64de29b234324676b5ee17e72d2e578be417a500b5d1fa546585f45a8fedb7dafb73e62964e49bc8f3900299f7744eeaa880dbe08b0218e4c8db0b9834bc7e83b21e299c2.JPG)

**Comment by grayce1220** [comment]
PF - ok

**Comment by LoreleiGab** [comment]
Testando...
