### ISSUE TITLE
SMC / Proponente

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#134]
Na parte e aprovação de inscrições (proponente pf e pj; incentivadores pf e pj) , adicionar um campo de nota para casos que os documentos foram aprovados, mas falta algum documento.
Esta nota precisa ficar disponível na informação da inscrição do proponente e incentivadores.

Verificar a disponibilidade de troca de documentos

parent of #163
Requires #163

**Comment by grayce1220** [comment]
ALTER TABLE `notas` CHANGE `idProjeto` `idPessoa` INT(11) NULL DEFAULT NULL;

UPDATE `notas` SET `idTipo`= 3;
