### ISSUE TITLE
COMISSÃO PRESIDENTE: Na Home, nenhum projeto está linkado.

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#137]
Usando o login com o "NÍVEL DE ACESSO COMISSÃO PRESIDENTE"

·         1- Na Home, nenhum projeto está linkado. Aparecem projetos com status "Enviado", mas não tem nenhum botão para enviar para Comissão, nem nenhum link. Conforme print abaixo:

**Comment by riquetinem** [comment]
[Uploading image003.jpg...]

**Comment by riquetinem** [comment]
![image003.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3f9dcabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb80bbb25884782b3b48c49c2ef3521f5c6.jpg)

**Comment by riquetinem** [comment]
Por ser comissão as funcionalidades da SMC

**Comment by DiegoVSantos** [comment]
Adicionado um redirect na "smc_index". Caso o nivel de acesso seja 3 (Comissão Presidente) ou 4 (Comissão Parecerista), o usuário é redirecionado para a "comissão_index"
