### ISSUE TITLE
SMC - na Home, incluir um botão ao lado do Visualizar para enviar os projetos para a Comissão sem ter que visualizá-los. Incluir somente em etapas que sejam pertinentes (2,13,14,23)

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#138]
2- Se eu entro na Pesquisa e digito o nome de algum projeto com o status de enviado e entro em "detalhes", aí sim eu consigo enviar para a Comissão. Conforme print abaixo. Mas seria mais fácil já conseguir entrar nos projetos e poder distribuir na Home mesmo.

**Comment by riquetinem** [comment]
[Uploading image005.jpg...]

**Comment by riquetinem** [comment]
![image005.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3f9daabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb60bbb25884782b3b58244c5eb3a27f5c6.jpg)

**Comment by LoreleiGab** [comment]
1- Criação de botão “Enviar para Comissão” na home para SMC passar os projetos direto para Comissão sem abrir. Botão deve ficar disponível apenas no nível de acesso SMC.

**Comment by grayce1220** [comment]
Testando

**Comment by grayce1220** [comment]
teste ok
