### ISSUE TITLE
COMISSÃO PRESIDENTE: Objeto não encontrado

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#139]
3- Eu entrei na caixa da parecerista Michelle e entrei em um projeto que estava com o status Reprovado, chamado "Academia das Artes". Cliquei no parecer que já estava incluso no sistema, conforme print abaixo. Mas o link deu "Objeto não encontrado" e não consegui acessar o arquivo, conforme 2º print.  O mesmo aconteceu com outros projetos, como São Paulo Verde, também "reprovado", e Bola dos Sonhos, que está com o status "certificados anexados". Não estou conseguindo acessar nenhum parecer, nem aqueles que precisam de aprovação da SMC para ficarem disponíveis, como é o caso do projeto "Artistas de Rua".

**Comment by riquetinem** [comment]
![image040.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3fddfabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901dbf0bbb25884782b3b58f4cc0e03520f5c6.jpg)

**Comment by riquetinem** [comment]
![image014.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3f8dbabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb80bbb25884782b3b58f44c5ef3923f5c6.jpg)

**Comment by grayce1220** [comment]
Por estar no ambiente de homologação, os arquivos não existem nesse servidor. Para testar e conseguir visualizar, deve criar um projeto novo.
