### ISSUE TITLE
COMISSÃO PRESIDENTE: Projetos em andamento sem numero de protocolo

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#140]
4- Tem 2 projetos que estão em análise e estão sem número de protocolo (nº ISP). Como isso pode acontecer? Deveria haver uma trava para só poder ir para Comissão depois de finalizado e com número de protocolo. São os projetos "Caminhos Cruzados" - Status: Complemento de informações pendente, e "Teste Duo2" - "Em análise SMC".  Conforme print abaixo:

**Comment by riquetinem** [comment]
![image016.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3f8d9abf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb60bbb25884782b3b48d44c5e8392cf5c6.jpg)

**Comment by riquetinem** [comment]
FuncoesGerais (function geraProtocolo) 
informacoes_adminisrativas

**Comment by grayce1220** [comment]
1 dos projetos sem protocolo trata-se de um teste do sistema, e provavelmente o envio foi forçado pelo banco o que nao possibilitou gerar o protocolo.

**Comment by LoreleiGab** [comment]
Teste OK
Como testei: verifiquei em todo o sistema pelo campo idStatus em busca de encontrar algum local que efetue o envio antes do momento correto.
