### ISSUE TITLE
COMISSÃO PRESIDENTE: Finalizar projeto e enviar à SMC?

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#141]
5- Eu finalizei um projeto (Nas Trilhas da Cidadania) e enviei para a SMC. Depois fui na área da SMC e entrei no projeto. E aparecia novamente a pergunta "Finalizar projeto e enviar à SMC?", conforme print abaixo. É errado estar com essa pergunta novamente, pois confunde o usuário. Eu cliquei em SIM de novo para ver o que acontecia. Olhei na "Área SMC" e o projeto simplesmente desapareceu de lá. Não sei para onde foi.

  6- Depois eu fui em Pesquisa e busquei o mesmo projeto e ele aparece sem status nenhum, conforme print abaixo:

·         7- Depois eu fui na aba Histórico e em Histórico de Reunião não aparece "Finalizado e enviado à SMC", conforme print abaixo:

**Comment by riquetinem** [comment]
![image024.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3fbdbabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901dbf0bbb25884782b0bc8e45c7ee3e21f5c6.jpg)

**Comment by grayce1220** [comment]
![semstats.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563801235ef3264700527c74/125516c66e82c728ace21e0d46fb9197309682bd9cabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb70bbb25884782b0ba8949c3e93b27f5c6.jpg)

**Comment by grayce1220** [comment]
![3.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563801235ef3264700527c74/125516c66e82c728ace21e0d46bbd6d6619291a685ecbc57e607b2c12b1121232807a27a74d7e271e8122b500b581cfa48595d56e0ebcb7af8e2632dd3165eafc3674d75c13710a9bb8a18b907be228a4e8dbeaec7.jpg)

**Comment by DiegoVSantos** [comment]
Fluxo OK
Alterações de Status aparecendo normalmente na aba "Histórico"
