### ISSUE TITLE
COMISSÃO PRESIDENTE: Sem status

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#142]
·         6- Depois eu fui em Pesquisa e busquei o mesmo projeto e ele aparece sem status nenhum, conforme print abaixo:

**Comment by riquetinem** [comment]
![image031.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3fadeabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901dbf0bbb25884782b3b48248c8e93f20f5c6.jpg)
