### ISSUE TITLE
COMISSÃO PRESIDENTE:Não aparece "Finalizado e enviado à SMC"

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#143]
Depois eu fui na aba Histórico e em Histórico de Reunião não aparece "Finalizado e enviado à SMC", conforme print abaixo

**Comment by riquetinem** [comment]
![image033.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3fadcabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb60bbb25884782b3b4834bc0e13a26f5c6.jpg)
