### ISSUE TITLE
SMC: o status foi alterado e ele aparece na aba "Área Comissão"

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#144]
Eu peguei um projeto que estava com status "enviado" e enviei para a Comissão, conforme print abaixo. O envio deu certo, o status foi alterado e ele aparece na aba "Área Comissão"

**Comment by grayce1220** [comment]
Fluxo correto. Quando se envia um projeto para a Comissão o status é alterado o status para OPROJETO ENVIADO À COMISSÃO, e deve ser exibido na aba da comissão.

**Comment by DiegoVSantos** [comment]
Fluxo Correto! Teste OK
