### ISSUE TITLE
Pareceristas que não estão mais na comissão

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#146]
Tem projetos que constam nas caixas de pareceristas que não estão mais na Comissão, como Milton e Neide. Não sei se isso é um erro de sistema ou da distribuição feita pela Michelle. No caso do projeto "Pedro e o Lobo" isso é importante porque ele ainda está em fase de tramitação na Comissão, então tem que estar com o parecerista certo para fazer a análise.

**Comment by riquetinem** [comment]
![image045.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3fddaabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901dbe0bbb25884782b0bd8b49c0ee3b20f5c6.jpg)

**Comment by riquetinem** [comment]
![image043.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3fddcabf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb60bbb25884782b0bd8b4bc0e83427f5c6.jpg)

**Comment by DiegoVSantos** [comment]
Aguardando resposta sobre nova funcionalidade de excluir usuarios

**Comment by LoreleiGab** [comment]
Ao invés de excluir um parecerista, eles irão mudar o nível de acesso para "proponente".
