### ISSUE TITLE
Consulta pública: projetos aprovados

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#147]
Na Consulta Pública, quando eu busco pelos projetos aprovados de forma geral, aparecem apenas 50, sendo que há mais do que 50 projetos aprovados mesmo antes de 01/10/18.

**Comment by riquetinem** [comment]
![image049.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46e1999b2487d3fdd6abf301b44fff9e2c4533317346f6292783b329bc432a055d0e47ab41585e10fbabdf22a7b42e6c981e5ab38532022d8c6853beb2901eb80bbb25884782b0bd884bc5e13c23f5c6.jpg)

**Comment by DiegoVSantos** [comment]
Precisamos da lista dos projetos aprovados até o dia 01/10/2018. Em pesquisa direta no banco de dados retorna 50 registros

**Comment by DiegoVSantos** [comment]
connects #164

**Comment by grayce1220** [comment]
Aguardando mudança de status

**Comment by riquetinem** [comment]
http://prntscr.com/l6g8jb
Teste OK, está aparecendo todos os projetos enviados.
