### ISSUE TITLE
1. No campo Consulta Pública, constam todos os dados pessoais do proponente como: N° RG, N° CPF e ENDEREÇO.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#152]

**Comment by LoreleiGab** [comment]
Foi mantido somente as informações de telefone e e-mail para representantes e pessoa física. No caso de pessoa jurídica foi incluído o endereço da empresa, conforme imagens:

![Capturar_pf.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563b68cd746ae64300e4e6d5/125516c66e82c728ace21e0d46cb958a379791a89dd6af45e611b2843b492d762a10e17132d0e17fb9127a020e5e1aae10515844fcf8dd2cf4e03571884e17ff933c0120996048e6edc00db513bb28814e80b5b58a4ec4e93c23e68c875d73.JPG)
![Capturar_pj.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563b68cd746ae64300e4e6d5/125516c66e82c728ace21e0d46cb958a379791a89dd6af49e611b2843b492d762a10e17132d0e17fb9127a020e5e1aae10515844fcf8dd2cf4e03571884e17ff933c0120996048e6edc00db513bb27814e80b5b58a4ec4e9352ce68b8f5d73.JPG)

**Comment by grayce1220** [comment]
TESTE OK
