### ISSUE TITLE
SMC - Label Adm - Erro Notas

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#160]
Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in C:\xampp\htdocs\promac\perfil\includes\label_smc_adm.php on line 144

**Comment by LoreleiGab** [comment]
Erro no meu banco de dados local devido a não alteração conforme abaixo:

ALTER TABLE notas CHANGE idProjeto idPessoa INT(11) NULL DEFAULT NULL;

ALTER TABLE notas
add column idTipo INT(11) DEFAULT '3';

**Comment by grayce1220** [comment]
TESTE OK
