### ISSUE TITLE
QUESTÃO 2 – PARECERES

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#162]
ETAPA 1

O parecerista insere o parecer e nós analisamos se o parecer está certo.

ETAPA 2

Parecer certo, APROVAMOS o parecer.

Parecer errado, REPROVAMOS  e eles inserem de novo ou nós mesmo podemos inseri-los.

Nas últimas semanas (3 ultimas) não conseguimos realizar essas tarefas, por erros como: o botão de inserir o parecer havia sumido (modulo comissão), não conseguimos excluir um parecer errado para o parecerista inserir de novo, a data não gravava e por isso os pareceres não subiam para o proponente.

Solicito cuidado nessa área e, se precisar, tirar informação e só ficar o que é importante, que é o botão para subir o parecer. Quanto mais simples for para o parecerista e para nós, melhor.

**Comment by LoreleiGab** [comment]
Testes para verificar se não há mais falhas

**Comment by grayce1220** [comment]
- se está aprovado o parecer, ele continua exibindo o botão de apagar (e não deveria). só pode exibir o botão de apagar se ainda não foi analisado ou se foi reprovado;
- não lista observação;

**Comment by LoreleiGab** [comment]
Feito

**Comment by riquetinem** [comment]
Teste OK
