### ISSUE TITLE
QUESTÃO 3 – HABILITAÇÃO

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#163]
ETAPA 1

O proponente inserir seus documentos para analisarmos.

ETAPA 2

SMC análisa os documentos e:

Se a documentação está certa - APROVA

Se a documentação está errada - REPROVA  e preenche ao lado o porquê da reprovação

Se tem documentação que o proponente esqueceu de inserir - APROVAMOS TODOS OS DOCUMENTOS, mas reprovamos a inscrição e dizemos porque reprovamos.

 

Não precisamos de mais nenhum campo, só garantir que consigamos avisar o proponente o que ele precisa fazer para ser aprovado.

PARENT OF #169
PARENT OF #173

**Comment by LoreleiGab** [comment]
Como avisar o proponente o que ele precisa fazer para ser aprovado?

**Comment by grayce1220** [comment]
Foi realizada task para campo de notas conforme  #169
