### ISSUE TITLE
Pesquisa de projeto por parecerista

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#167]
Em cima, Lista os projetos vinculados e abaixo, organizar os projetos por status (como na index smc).
Exibir somente os projetos viculados ao parecerista selecionado

**Comment by DiegoVSantos** [comment]
Aguardando para concluir nova funcionalidade. Progresso na nova branch "historico-parecerista#167"

**Comment by riquetinem** [comment]
Teste OK
