### ISSUE TITLE
reabilitar notas

### ISSUE THREAD

**Issue by grayce1220** [igsis/promac#169]
PARENT OF #173

**Comment by LoreleiGab** [comment]
Para liberado = 1 foi trocado de textarea para input e removido o botão de gravar, que agora está embutido com os botões de aprovar e não aprovar.
Para liberado = 2, 3 ou 4 aparece apenas uma lista com as notas inseridas para aquela pessoa ou um aviso que não há notas inseridas.
No teste verificar se tudo está gravando devidamente, principalmente em incentivador_pj, pois não havia o if para $pj['liberado'] == 3

**Comment by LoreleiGab** [comment]
2- Criação de campo “Notas” na parte de Habilitação de Proponentes para SMC conseguir informar ao proponente qual documento faltou ou está errado.

**Comment by grayce1220** [comment]
Testando

**Comment by grayce1220** [comment]
Teste ok
