### ISSUE TITLE
Proponente - Mensagem ao anexar certificado, recurso, complemento ou solicitação de alteração

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#170]
Atual: Certifique-se que sua documentação está correta antes do envio. Em caso de substituição, deverá ser solicitado à equipe da SMC.

Corrigir para: Certifique-se que sua documentação está correta antes do envio.

**Comment by riquetinem** [comment]
Teste ok

![Screenshot_3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf71fbcd6395428792c07b7692ac7b62ae8442b000c0e4ff843095643fcf9887fa1e46a798b5e19f1c32f0e2a92624cf5f2d75dad0ba8228b4584b3bf834dc1ed3b21e28386472c53.png)

**Comment by grayce1220** [comment]
![modal-atencao.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563801235ef3264700527c74/125516c66e82c728ace21e0d46e59b9e228ecea89becb140a552b2d86b56357c2301a03f32dfa17dbd157d510e0c1fad155a0e4dfbf9892af2b16e26835d09ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98945c1e9382de58b8a4a3c0c48.JPG)
