### ISSUE TITLE
Erro no modal em projeto_visualizacao

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#171]
Ao visualizar um projeto já inscrito, quando clica-se na aba "projetos", ainda aparece o conteúdo da aba "Informações da Inscrição"

**Comment by LoreleiGab** [comment]
Corrigido o local onde estava o include do modal de projetos

**Comment by lucasdauto** [comment]
Testando

**Comment by lucasdauto** [comment]
Teste ok
