### ISSUE TITLE
5- Mudar os nomes dos status de parecer: “Aprovado” passa a ser “Aceito” e “Reprovado” passa a ser “Negado”. Isso ajuda a não confundirmos com a nomenclatura usada para os projetos.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#176]

**Comment by grayce1220** [comment]
UPDATE `status_documento` SET `status` = 'Aceito' WHERE `status_documento`.`idStatusDocumento` = 1; UPDATE `status_documento` SET `status` = 'Negado' WHERE `status_documento`.`idStatusDocumento` = 3;

**Comment by LoreleiGab** [comment]
Feito
