### ISSUE TITLE
7- Histórico do projeto: seria interessante uma aba de Histórico do Projeto que informasse todas as alterações do projeto, tanto de mudança de etapas quanto de inclusão ou exclusão de documentos. A Lore me informou que a parte de mostrar as inclusões e alterações de documentos é muito difícil de se fazer agora, então o que poderíamos ter por agora é apenas o histórico de mudança de etapas.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#178]

**Comment by LoreleiGab** [comment]
[detalhes_7.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563b68cd746ae64300e4e6d5/125516c66e82c728ace21e0d46ec918e228e8bac9cd6e801e81fe086264c22703d46f9692587b42eef4378005e0b4cfd485f5f44fdad8e79f0bf3d72984019af80330b2b9b645bf9fa9015ad00b22a8a4a86bfbd824ac5eb3920e4889d02.docx)

**Comment by LoreleiGab** [comment]
- Removido o histórico de reunião e histórico de publicação

**Comment by LoreleiGab** [comment]
Etapas
- Proponente -> SMC - OK
- SMC -> Comissão - OK

**Comment by riquetinem** [comment]
Teste OK
