### ISSUE TITLE
Ambiente SMC - Criar um formulario para cadastro para o link de agendamento

### ISSUE THREAD

**Issue by riquetinem** [igsis/promac#206]

**Comment by Tannair** [comment]
CREATE TABLE IF NOT EXISTS `mydb`.`agendamento` ( 
 `id` INT NOT NULL AUTO_INCREMENT,
  `linkAgendamento` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id`)
);

**Comment by DiegoVSantos** [comment]
TESTE OK

Como o campo "linkAgendamento" irá guardar links, o VARCHAR foi aumentado para 150
