### ISSUE TITLE
Módulo Proponente - PF - Lista de documentos, colocar um modelo para download no item "F" - Declaração, conforme modelo em Anexo I.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#212]
Modelo do anexo I dos regulamentos

PREFEITURA DA CIDADE DE SÃO PAULO
SECRETARIA MUNICIPAL DE CULTURA
Coordenadoria de Incentivo à Cultura – Pro-Mac
16
Anexo I
DECLARAÇÃO DE INSCRIÇÃO DE PROPONENTE
Cabeçalho para Proponente Pessoa Jurídica
Eu, ......................., RG nº .............., CPF nº.............., representante legal da pessoa jurídica
......................., CNPJ n°........................., sediada no endereço ..............................., bairro
......................., CEP...................., município de ............................, venho declarar que:
Cabeçalho para Proponente Pessoa Física:
Eu, ......................., RG nº .............., CPF nº.............., residente no endereço ...........................,
bairro ......................., CEP...................., município de ..........................., venho declarar que:
a) Tenho ciência e concordo com os termos da Lei nº 15.948/2013, do Decreto nº
58.041/2017 e desta portaria;
b) As informações prestadas são verídicas;
c) Sou residente / sediado no Município de São Paulo há no mínimo 02 (dois) anos;
d) Não possuo qualquer associação ou vínculo direto ou indireto com empresas de
serviços de radiodifusão de som e imagem ou operadoras de comunicação eletrônica
aberta ou por assinatura;
e) Não possuo qualquer associação ou vínculo direto ou indireto com o contribuinte
incentivador do projeto apresentado, ressalvadas as hipóteses a que aludem o inciso
XX do artigo 4º e o inciso III do artigo 7º da Lei nº15.948/2013;
f) Estou em situação regular perante a Administração Pública;
g) Não estou cadastrado e não possuo débitos junto à Fazenda do Município de São
Paulo;
h) O projeto apresentado não recebeu e nem recebe recursos de editais da Secretaria
Municipal de Cultura.
Acréscimo somente para proponente PJ:
i) Não emprego menor de dezoito anos em trabalho noturno, perigoso ou insalubre e
não emprego menor de 16 anos, salvo na condição de aprendiz;
j) Não tenho entre os dirigentes pessoa cujas contas relativas a parcerias tenham sido
julgadas irregulares ou rejeitadas por Tribunal ou Conselho de Contas de qualquer
esfera da Federação, em decisão irrecorrível, nos últimos 8 (oito) anos; julgada
responsável por falta grave e inabilitada para o exercício de cargo em comissão ou
função de confiança, enquanto durar a inabilitação; ou considerada responsável por
ato de improbidade, enquanto durarem os prazos estabelecidos nos incisos I, II e III do
art. 12 da Lei nº 8.429/1992.
________________________________
Proponente

**Comment by LoreleiGab** [comment]
UPDATE `lista_documento` SET `documento` = 'Declaração de inscrição [modelo para download]' WHERE `lista_documento`.`idListaDocumento` = 6;

**Comment by LoreleiGab** [comment]
UPDATE lista_documento SET documento = 'Declaração de inscrição [modelo para download]' WHERE lista_documento.idListaDocumento = 15;

**Comment by riquetinem** [comment]
TESTE ok
