### ISSUE TITLE
22- Tornar inserção obrigatória   :   Documentação para Proponente Pessoa Jurídica (não cooperativa)

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#215]
a) Cartão do CNPJ; b) Ato constitutivo (estatuto ou contrato social) devidamente registrado, comprovando no objeto atividades artísticas ou culturais nos últimos 02 (dois) anos. A comprovação referida também poderá ser efetuada por meio de apresentação de portfólio; c)Ata de Eleição e Posse de seus administradores, quando for o caso; ( não obrigatório )
d) Cadastro de Contribuintes Mobiliários - C.C.M.;
e) RG ou RNE do representante legal;
f) CPF do representante legal;
g) Comprovante de endereço atual (até últimos 03 meses da inscrição) no Município de
São Paulo da sede pessoa jurídica;
h) Comprovante de endereço de pelo menos 02 (dois) anos no Município de São Paulo da
sede da pessoa jurídica;
i) Declaração, conforme modelo em Anexo I; ( mesma da PF - colocar o link para o modelo )

Child of #216

**Comment by lucasdauto** [comment]
a)7,b)9 ou 16,c)10,d)8,e)11,f)12,g)13,h)14,i)15

**Comment by DiegoVSantos** [comment]
Parent of #216

**Comment by DiegoVSantos** [comment]
Verificado! OK!
