### ISSUE TITLE
23- Tornar inserção obrigatória : Documentação para Proponente Pessoa Jurídica - COOPERATIVA

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#216]
1. Cartão do CNPJ;
2. Ato constitutivo (estatuto ou contrato social) devidamente registrado, comprovando no objeto atividades artísticas ou culturais nos últimos 02 (dois) anos. A comprovação referida também poderá ser efetuada por meio de apresentação de portfólio;
3. Ata de Eleição e Posse de seus administradores, quando for o caso; ( não obrigatório )
4. Cadastro de Contribuintes Mobiliários - C.C.M.;
5. RG ou RNE do representante legal;
6. CPF do representante legal;
7. Comprovante de endereço atual (até últimos 03 meses da inscrição) no Município de São Paulo da sede pessoa jurídica;
8. Comprovante de endereço de pelo menos 02 (dois) anos no Município de São Paulo da sede da pessoa jurídica;
9. Declaração, conforme modelo em Anexo I; ( mesma da PF - colocar o link para o modelo )
10. No caso de proponente Cooperativa, apresentar também: Certidão de Regularidade da Cooperativa perante a Organização das Cooperativas Brasileiras ou Organização das Cooperativas do Estado de São Paulo - OCESP.

**Comment by LoreleiGab** [comment]
Consegui enviar a inscrição mesmo sem nenhum documento anexado

**Comment by DiegoVSantos** [comment]
- Portfolio não é um documento obrigatório
- Caso o proponente não seja "Cooperativa", o documento do item 10 não deve ser solicitado

**Comment by lucasdauto** [comment]
Corrigido

**Comment by DiegoVSantos** [comment]
Verificado! OK!
