### ISSUE TITLE
30- criar coluna de contagem de dias de quanto tempo o projeto está na caixa do parecerista ( a partir do momento que foi atribuído - não zerar data  ao mudar de parecerista

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#223]

**Comment by DiegoVSantos** [comment]
Atualmente, a coluna foi adicionada às etapas onde o Projeto está com a SMC. Esta deve estar nas etapas de ID: 7, 19, 24 e 34

**Comment by DiegoVSantos** [comment]
A data deve ser atualizada qdo á um novo envio do projeto à comissão

**Comment by DiegoVSantos** [comment]
**O que foi feito:** Quando um projeto é enviado à comissão a partir da etapa 2 "Enviado", a "data do parecerista" começa a contar a partir da primeira atribuição de um parecerista responsável.
Quando este envia de volta o projeto à SMC, a data é zerada.
Quando um projeto é enviado à comissão a partir das demais etapas, é atribuído à "data do parecerista" a data atual

**Comment by lucasdauto** [comment]
Teste ok
