### ISSUE TITLE
31- quando der maior ou igual a 30 dias parado na caixa do parecerista - aparecer em vermelho

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#224]
Requires #223

**Comment by Tannair** [comment]
ALTER TABLE `projeto` ADD `dataParecerista` DATE NOT NULL AFTER `idStatusParecerista`;

**Comment by DiegoVSantos** [comment]
Atualmente, a função foi adicionada às etapas onde o Projeto está com a SMC. Esta deve estar nas etapas de ID: 7, 19, 24 e 34

**Comment by DiegoVSantos** [comment]
Verificado! OK!
