### ISSUE TITLE
37- liberar de 1 em 1 para a presidente. só aparece o segundo depois de atribuído o anterior. limite 50 por semana.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#229]
No ambiente Comissão, na tela da diretoria da comissão, liberar aparecimento dos projetos apenas de 1 em 1, na ordem de protocolo ASC, porém, só liberar no máximo de 50 projetos por semana.

**Comment by DiegoVSantos** [comment]
Como identificar que o projeto foi "Tratado" para passar para o próximo?

**Comment by DiegoVSantos** [comment]
Está conflitando com a Issue #235
Pois quando o projeto está cancelado, a presidente da comissão não pode trata-lo e prosseguir
