### ISSUE TITLE
41- bloqueio automático do período de inscrição. Por data. Somente uma pessoa responsável poderá ter acesso a esta função.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#231]
Criar uma tela para cadastrar data e hora que o sistema deve abrir ou deve fechar. Liberar somente para a chefia de SMC (criar esse novo nível de acesso)

**Comment by Tannair** [comment]
ALTER TABLE `promac`.`statusprojeto` 
ADD COLUMN `dataLiberacao` DATE NOT NULL AFTER `descricaoSituacao`,
ADD COLUMN `dataBloqueio` DATE NOT NULL AFTER `dataLiberacao`, RENAME TO  `promac`.`liberacaoprojeto` ;

**Comment by LoreleiGab** [comment]
ALTER TABLE promac.statusprojeto
ADD COLUMN data DATE NOT NULL AFTER descricaoSituacao, RENAME TO promac.liberacao_projeto ;

**Comment by riquetinem** [comment]
TESTE OK
