### ISSUE TITLE
43- Habilitar botão de cancelamento do projeto no módulo do proponente. Ele poderá cancelar a qualquer momento.

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#234]

**Comment by LoreleiGab** [comment]
Falta modal solicitando o motivo do cancelamento, idêntico ao utilizado no ambiente da SMC

**Comment by LoreleiGab** [comment]
Verificar se foi dado merge na branch desenvolvimento

**Comment by DiegoVSantos** [comment]
Confirmar o merge

**Comment by lucasdauto** [comment]
Foi dado merge

**Comment by LoreleiGab** [comment]
Ainda não tem o motivo do cancelamento

**Comment by LoreleiGab** [comment]
TESTANDO
