### ISSUE TITLE
47- Excluir a lista de upload de arquivo (parecer)

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#238]

**Comment by lucasdauto** [comment]
Child of #240

**Comment by LoreleiGab** [comment]
TESTANDO

**Comment by LoreleiGab** [comment]
Ao remover a parte de exibição dos arquivos do parecer do ambiente da SMC, sumiu também no ambiente da Comissão e isso não pode acontecer.

**Comment by LoreleiGab** [comment]
TESTE - OK
