### ISSUE TITLE
50 - Nota de explicação do termo de responsabilidade: - O documento deve ser entregue na SMC pelo proponente ou por um representante com a devida procuração simples original; - em caso de Cooperativa, a Cooperativa deve assinar e o Proponente como anuente. - No momento da entrega do termo será expedido o ofício da abertura de conta e a autorização de captação.

### ISSUE THREAD

**Issue by riquetinem** [igsis/promac#243]

**Comment by riquetinem** [comment]
BOTAO DO MODAL 

                                            <button class='btn btn-default' type='button' data-toggle='modal' data-target='#termoResponsabilidade' style="border-radius: 30px;"><i class="fa fa-question-circle"></i></button>


MODAL

<div class="modal fade" id="termoResponsabilidade" role="dialog" aria-labelledby="termoResponsabilidade" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title">Termo de Responsabilidade</h4>
                                        </div>
                                        <div class="modal-body" style="text-align: left;">
                                            <div role="tabpanel">
                                                <div class="tab-content">
                                                    
                                                    <div role="tabpanel" class="tab-pane fade in active" id="tabela">
                                                        <br>
                                                        <div class="well">
                                                            O documento deve ser entregue na SMC pelo proponente ou por um representante com a devida procuração simples original; - em caso de Cooperativa, a Cooperativa deve assinar e o Proponente como anuente. - No momento da entrega do termo será expedido o ofício da abertura de conta e a autorização de captação.
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

**Comment by riquetinem** [comment]
BOTAO DO MODAL

                                            <button class='btn btn-default' type='button' data-toggle='modal' data-target='#termoResponsabilidade' style="border-radius: 30px;"><i class="fa fa-question-circle"></i></button>

**Comment by riquetinem** [comment]
MODAL

                            <div class="modal fade" id="termoResponsabilidade" role="dialog" aria-labelledby="termoResponsabilidade" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title">Termo de Responsabilidade</h4>
                                        </div>
                                        <div class="modal-body" style="text-align: left;">
                                            <div role="tabpanel">
                                                <div class="tab-content">
                                                    
                                                    <div role="tabpanel" class="tab-pane fade in active" id="tabela">
                                                        <br>
                                                        <div class="well">
                                                            O documento deve ser entregue na SMC pelo proponente ou por um representante com a devida procuração simples original; - em caso de Cooperativa, a Cooperativa deve assinar e o Proponente como anuente. - No momento da entrega do termo será expedido o ofício da abertura de conta e a autorização de captação.
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

**Comment by DiegoVSantos** [comment]
Teste OK!
