### ISSUE TITLE
51 - Nota de certidões: - Não será aceito nenhum protocolo de pagamento ou correla do. Somente são válidas certidões negativas ou positivas com efeito de negativa.

### ISSUE THREAD

**Issue by riquetinem** [igsis/promac#244]

**Comment by riquetinem** [comment]
Botão do modal

                                            <button class='btn btn-default' type='button' data-toggle='modal' data-target='#certidaoFiscal' style="border-radius: 30px;"><i class="fa fa-question-circle"></i></button>

**Comment by riquetinem** [comment]
MODAL 


                            <div class="modal fade" id="certidaoFiscal" role="dialog" aria-labelledby="certidaoFiscal" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title">Certidões Fiscais</h4>
                                        </div>
                                        <div class="modal-body" style="text-align: left;">
                                            <div role="tabpanel">
                                                <div class="tab-content">
                                                    
                                                    <div role="tabpanel" class="tab-pane fade in active" id="tabela">
                                                        <br>
                                                        <div class="well">
                                                            Não será aceito nenhum protocolo de pagamento ou correla do. Somente são válidas certidões negativas ou positivas com efeito de negativa.
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

**Comment by DiegoVSantos** [comment]
Teste OK!
