### ISSUE TITLE
52 - Nota da carta de intenção: Quando houver um incentivador, favor preencher a carta de incentivo, conforme modelo em anexo e entregar pessoalmente na SMC nos casos de incentivo iguais ou acima de R$ 80 mil.

### ISSUE THREAD

**Issue by riquetinem** [igsis/promac#245]

**Comment by riquetinem** [comment]
BOTAO DO MODAL

                                            <button class='btn btn-default' type='button' data-toggle='modal' data-target='#cartaIntencaoIncentivo' style="border-radius: 30px;"><i class="fa fa-question-circle"></i></button>

**Comment by riquetinem** [comment]
MODAL


                            <div class="modal fade" id="cartaIntencaoIncentivo" role="dialog" aria-labelledby="cartaIntencaoIncentivo" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title">Carta de Intenção de Incentivo</h4>
                                        </div>
                                        <div class="modal-body" style="text-align: left;">
                                            <div role="tabpanel">
                                                <div class="tab-content">
                                                    
                                                    <div role="tabpanel" class="tab-pane fade in active" id="tabela">
                                                        <br>
                                                        <div class="well">
                                                            Quando houver um incentivador, favor preencher a carta de incentivo, conforme modelo em anexo e entregar pessoalmente na SMC nos casos de incentivo iguais ou acima de R$ 80 mil.                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

**Comment by DiegoVSantos** [comment]
Teste OK!
