### ISSUE TITLE
65 - em valores de enquadramento é preciso separar campos: exposição da marca e indicação do valor do ingresso. no box exposição da marca ser lista suspensa com as opções: APRESENTA /PATROCINIO / APOIO/ MECENATO

### ISSUE THREAD

**Issue by riquetinem** [igsis/promac#258]

**Comment by LoreleiGab** [comment]
CREATE TABLE `exposicao_marca` (
 `id` tinyint(1) NOT NULL,
 `exposicao_marca` varchar(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `exposicao_marca` (`id`, `exposicao_marca`) VALUES
(1, 'Apresenta'),
(2, 'Patrocínio'),
(3, 'Apoio'),
(4, 'Mecenato');

ALTER TABLE `exposicao_marca`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `exposicao_marca`
 MODIFY `id` tinyint(1) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

**Comment by DiegoVSantos** [comment]
Teste OK!
