### ISSUE TITLE
INSCRIÇÃO DE PROJETO - Local

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#270]
* **Tela:** 
Cadastro de Projeto - Local 

* **Problema:**
Área do "Público estimado" não está legível quando se digita o número, só aparece o primeiro digito. Depois que clica inserir ele aparece. Retirar os campos Zona, Prefeitura Regional e Distrito. Colocar: Endereço/Nº/Complemento/Bairro/CEP

**Comment by DiegoVSantos** [comment]
**DESCRIÇÃO**

**Comment by LoreleiGab** [comment]
ALTER TABLE `locais_realizacao` ADD `logradouro` VARCHAR(150) NOT NULL AFTER `estimativaPublico`, ADD `numero` INT(5) NOT NULL AFTER `logradouro`, ADD `complemento` VARCHAR(15) NOT NULL AFTER `numero`, ADD `bairro` VARCHAR(30) NOT NULL AFTER `complemento`, ADD `cidade` VARCHAR(50) NOT NULL AFTER `bairro`, ADD `estado` CHAR(2) NOT NULL AFTER `cidade`, ADD `cep` CHAR(9) NOT NULL AFTER `estado`;

**Comment by DiegoVSantos** [comment]
TESTE OK
