### ISSUE TITLE
INSCRIÇÃO DE PROJETO - Orçamento

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#271]
* **Tela:** 
Cadastro de Projeto - Orçamento 

* **Problema:**
Ficaram ótimas as alterações, mas reparei que o campo Valor Unitário está pequeno. Se eu digito 100.000,00, o campo só mostra 100.00, parecendo que são 100 reais. Acho que mais que 5 digitos ele não mostra direito, seria bom aumentar.

**Comment by DiegoVSantos** [comment]
**DESCRIÇÃO**

**Comment by LoreleiGab** [comment]
Com o aumento do campo Valor Unitário, foi necessário diminuir o tamanho do campo Etapa, já que os campos estão utilizando a capacidade máxima do tamanho da linha sem desconfigurar a tela, permitindo que as informações do sistema ainda de ajustem a qualquer tamanho de tela de computador, tablet ou celular.

**Comment by DiegoVSantos** [comment]
TESTE OK
