### ISSUE TITLE
INSCRIÇÃO DE PROJETO - Valor Enquadramento

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#272]
* **Tela:** 
Cadastro de Projeto - Valor Enquadramento

* **Problema:**
Ótimas as alterações, mas no campo Valor Total do Projeto, que é digitável, não está configurado como $$$$. Eu digitei 50mil, mas não aparecem os pontos e vírgulas de númeração de dinheiro. Digitei manualmente ponto e vírgula, mas aí ficou como 50 reais, então é melhor colocar automaticamente como no orçamento.

**Comment by DiegoVSantos** [comment]
**DESCRIÇÃO**

**Comment by LoreleiGab** [comment]
Colocado o id="valor" no campo

**Comment by DiegoVSantos** [comment]
adicionado função "DinheiroDeBR" no POST

TESTE OK
