### ISSUE TITLE
INSCRIÇÃO DE PROJETO - Link do Youtube

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#273]
* **Tela:** 
Cadastro de Projeto - Link do Youtube

* **Problema:**
1. Mas quando eu ponho gravar, o vídeo aparece como gravado mas não aparece a imagem do vídeo, não sei se é pq Youtube é barrado aqui na SMC. Ver se tá tudo ok. 
2. Mudar o nome da Tela para Mídias Sociais para ficar de acordo com o Resumo. Aí coloca Mídias Sociais Link 1 Link 2 igual tá o do Youtube. E deixa a parte Links do Youtube embaixo do jeitinho que está hoje.

**Comment by DiegoVSantos** [comment]
**DESCRIÇÃO**

**Comment by LoreleiGab** [comment]
ALTER TABLE `projeto` ADD `midia_social_1` VARCHAR(60) NOT NULL AFTER `totalOutrosFinanciamentos`, ADD `midia_social_2` VARCHAR(60) NOT NULL AFTER `midia_social_1`;

**Comment by DiegoVSantos** [comment]
TESTE OK
