### ISSUE TITLE
INSCRIÇÃO DE PROJETO - Dados do Projeto - Aba PROJETO

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#276]
* **Tela:**
Aba PROJETO

* **Problema:**
Não apareceu a exposição de marca registrada na inscrição

**Comment by LoreleiGab** [comment]
Resolvido na issue #274 Revisado os campos da conclusão da inscrição de acordo com os campos preenchidos no sistema

**Comment by DiegoVSantos** [comment]
Ajustado também no resumo do projeto após seu envio

TESTE OK
