### ISSUE TITLE
PARECERISTA COMISSÃO - Confirmação de envio

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#279]
* **Tela:**
Confirmação de envio

* **Problema:**
Eu não sei se era a internet no momento do teste, mas estava um pouco lenta a confirmação do envio à SMC. Cliquei em "Confirmar" algumas vezes e nunca finalizava. Daí eu saí e entrei de novo no sistema e já havia sido enviado. Conferir se isso está normal ou não.

**Comment by riquetinem** [comment]
Provavelmente foi o problema de internet, pois aqui não deu nada
