### ISSUE TITLE
PARECERISTA - ANALISAR COMPLEMENTO E APROVAR

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/promac#285]
* **Tela:**
Inserir parecer, alterar dados, e enviar a SMC

* **Problema:**
Mesma requisição da linha 62 (**Issue #281**): É possível que o parecerista envie o projeto para SMC sem o valor aprovado, mesmo em caso de status APROVADO. Precisamos barrar isso, ou seja, colocar o campo "Valor Aprovado" como de preenchimento obrigatório apenas para o caso de ANÁLISE DO PARECERISTA: APROVADO

**Comment by LoreleiGab** [comment]
Feito na issue #281
