### ISSUE TITLE
INSCRIÇÃO COMO INCENTIVADOR (Demanda SMC)

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#290]
"PRECISAMOS DE UMA ALTERAÇÃO QUE NÃO HAVIA SIDO PENSADA ANTES, MAS AGORA TIVEMOS ALGUNS PROBLEMAS RELACIONADOS A ISSO E PENSAMOS NA SOLUÇÃO: 

Precisamos de algo parecido com o campo de inscrição de proponentes, onde há uma diferença entre os documentos exigidos para CNPJ e CPF. O que precisamos nesse caso é que antes de para fazer upload dos documentos haja um campo de escolha ""Você vai aportar utilizando ( ) ISS e/ou ( ) IPTU?"", (a pessoa deve poder clicar em 1 ou nas 2 opções, pois é possível utilizar IPTU E ISS juntos), então temos 3 opções: 

SE MARCAR SÓ ISS - lista de documentos que deve aparecer para a pessoa fazer o upload (barrar o envio se estiver faltando documentos): 

CNPJ                
Cadastro de Contribuintes Mobiliários - CCM        
Contrato Social
Comprovante de endereço atual (até últimos 3 meses)
CPF do Representante Legal        
Contrato de locação
Demonstrativo de ISS do ano anterior

SE MARCAR SÓ IPTU  - lista de documentos que deve aparecer para a pessoa fazer o upload (barrar o envio se estiver faltando documentos): ( a diferença é apenas o carnê de IPTU)

CNPJ                
Cadastro de Contribuintes Mobiliários - CCM        
Contrato Social
Comprovante de endereço atual (até últimos 3 meses)
Carnê IPTU
CPF do Representante Legal        
Contrato de locação

SE MARCAR ISS E IPTU - lista de documentos que deve aparecer para a pessoa fazer o upload (barrar o envio se estiver faltando documentos): 

CNPJ                
Cadastro de Contribuintes Mobiliários - CCM        
Contrato Social
Comprovante de endereço atual (até últimos 3 meses)
CPF do Representante Legal        
Contrato de locação
Demonstrativo de ISS do ano anterior
Carnê do IPTU

"

**Comment by DiegoVSantos** [comment]
Resumindo:

- [ ] Inserir Check-Box para incentivador selecionar ISS e/ou IPTU (ou os dois)
OBS: Barrar envio de inscrição caso não tenha todos os documentos

* Lista de documentos somente ISS:
CNPJ
Cadastro de Contribuintes Mobiliários - CCM
Contrato Social
Comprovante de endereço atual (até últimos 3 meses)
CPF do Representante Legal
Contrato de locação
Demonstrativo de ISS do ano anterior

* Lista de documentos somente IPTU:
CNPJ
Cadastro de Contribuintes Mobiliários - CCM
Contrato Social
Comprovante de endereço atual (até últimos 3 meses)
Carnê IPTU
CPF do Representante Legal
Contrato de locação

* Lista de documentos ISS e IPTU:
CNPJ
Cadastro de Contribuintes Mobiliários - CCM
Contrato Social
Comprovante de endereço atual (até últimos 3 meses)
CPF do Representante Legal
Contrato de locação
Demonstrativo de ISS do ano anterior
Carnê do IPTU
