### ISSUE TITLE
Ajustar a validação de quantidade de projetos por pessoa para projetos aprovados/reprovados parent of #185

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#48]

**Comment by LoreleiGab** [comment]
Deve ser:
Pessoa Física = 01
Pessoa Jurídica = 02
Pessoa Jurídica Cooperativa = ilimitado, porém apenas 01 por cooperado

**Comment by grayce1220** [comment]
rever por conta da regra do cancelado.

**Comment by LoreleiGab** [comment]
Função revista
Foi colocado na função que conta a quantidade de projetos para contar todos diferentes de idStatus = 6 (cancelado)
