### ISSUE TITLE
SMC - Criar e separar listagens na Home

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#84]
Colocar na Home duas abas (modal): Uma chamada SMC e outra chamada Comissão.
Criar um include com todas as informações que já existem na SMC.
No outro include criar uma lista com todos os projetos que estão com algum status que indique que o projeto está na Comissão. Incluir a coluna status e parecerista.

**Comment by DiegoVSantos** [comment]
**O que foi feito:** Caso o usuario tenha Nivel de Acesso 2 (SMC), é possivel liberar incrições de Proponentes e Incentivadores PF e PJ, visualizar os detalhes dos projetos com a SMC e Comissão e pesquisar por todos os status.
Caso seja nivel 3 (Comissão - Presidente) fica oculto as liberações de inscrição, só é possivel ver detalhes dos projetos que estão com a Comissão e pesquisar somente pelos status que estão na "Área Comissão"

**Comment by LoreleiGab** [comment]
TESTE - OK
