### ISSUE TITLE
Comissão - Criar e separar listagens na Home

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/promac#91]
Colocar na Home duas abas (modal): Uma chamada Comissão e outra chamada SMC.
Criar um include com todas as informações que já existem na Comissão.
No outro include criar uma lista com todos os projetos organizados por ordem de data de envio a SMC decrescente e que estão com alguma etapa que indique que o projeto NÃO está na Comissão. Limitar para os últimos 30 dias. Incluir a coluna etapa e parecerista.
Adicionar um botão de "ver todos", onde não existirá a função LIMIT.

**Comment by DiegoVSantos** [comment]
**O que foi feito:** Adaptei a index SMC para visualização por parte da Comissão, limitando visualizar detalhes dos projetos, pois ainda não existe uma trava q impeça o parecerista de alterar o projeto que está na SMC

**Comment by LoreleiGab** [comment]
Testando...
