### ISSUE TITLE
Validação no Cadastro de Incentivador

### ISSUE THREAD

**Issue by isaiaszmendes** [igsis/promac#94]
Erro documentado em anexo!

[erro_id_94.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b854666ef171800113a54dc/125516c66e82c728ace21e0d46ed86882cbd8aadb0b0eb01e81fe086264c22703d46f9692587b42eef4378005e0b4cfd485f5f44fdad8e79f0bf3d72984019af80330b2b9b645bf9fa9015ad00b22a8a4a86bebd8e45c7eb3d22e68d9d02.docx)

**Comment by isaiaszmendes** [comment]
Upload em andamento

**Comment by isaiaszmendes** [comment]
Desc

**Comment by riquetinem** [comment]
Teste OK
